#docker-compose.yml
version: '2'
  
  subgen:
    container_name: subgen
    network_mode: host
    image: rollingpixels/subgen
    environment:
       - "WHISPER_MODEL=medium"
       - "WHISPER_SPEEDUP=False"
       - "WHISPER_THREADS=4"
       - "WHISPER_PROCESSORS=1"
       - "WHISPER_CUBLAS=1"
       - "PROCADDEDMEDIA=True"
       - "PROCMEDIAONPLAY=False"
       - "NAMESUBLANG=aa"
       - "UPDATEREPO=True"
       - "SKIPIFINTERNALSUBLANG=eng"
       - "PLEXTOKEN=plextoken"
       - "PLEXSERVER=http://plexserver:32400"
       - "WEBHOOKPORT=8090"
    volumes:
       - "${TV}:/tv"
       - "${MOVIES}:/movies"
       - "${APPDATA}/subgen:/whisper.cpp"
